### ISSUE TITLE
iPhoneX上不兼容问题，如图

### ISSUE THREAD

**Issue by erduoniba** [lifution/FSActionSheet#6]
![image](https://user-images.githubusercontent.com/6082855/34346194-43bfd7da-ea30-11e7-9364-16442bd93e64.png)

**Comment by lifution** [comment]
近期会重构该项目, 适配iOS11和iPhone X. 😀

**Comment by erduoniba** [comment]
@lifution 麻烦看一下这里，兼容iPhoneX的安全区域代码我已经上传了哦。
https://github.com/lifution/FSActionSheet/pull/7

**Comment by lifution** [comment]
已经merge, 请看最新代码. 😊

**Comment by erduoniba** [comment]
非常感谢！有空做一个新的pod哦，我项目先使用你的git地址进行引入了，好了麻烦也记得@一下我哦。😊

**Comment by lifution** [comment]
我打算改成继承 `UIViewController` 重构的, 把 `FSActionSheet` 重构成 `FSActionSheetController`, 所以下一个版本改动会非常大, 你先修改你的pod里面的源码, 我的重构工作应该就是这星期内完成. 到时候如果你继续使用 `FSActionSheetController` 的话, 你需要把 `FSActionSheet` 迁移到 `FSActionSheetController`. 先提前跟你说一声. 😀

**Comment by erduoniba** [comment]
好的

**Comment by lifution** [comment]
@erduoniba 新版本已经更新了Cocoapods了, 你 `pod update` 一下就行. 😀
